#RequestRateLimiter 过滤器可以用于限流
server:
  port: 9201
#spring:
#  redis:
#    host: 47.100.93.46
#    password: 123456
#    port: 6379
#  cloud:
#    gateway:
#      routes:
#      - id: requestratelimiter_route
#        uri: http://localhost:8201
#        filters:
#        - name: RequestRateLimiter
#          args:
#            redis-rate-limiter.replenishRate: 1 #每秒允许处理的请求数量
#            redis-rate-limiter.burstCapacity: 2 #每秒最大处理的请求数量
#            key-resolver: "#{@ipKeyResolver}" #限流策略，对应策略的Bean
#        predicates:
#        - Method=GET
#logging:
#  level:
#    org.springframework.cloud.gateway: debug

spring:
  cloud:
    gateway:
      routes:
      - id: retry_route
        uri: http://localhost:8201
        predicates:
        - Method=GET
        filters:
        - name: Retry
          args:
            retries: 1 #需要进行重试的次数
            statuses: BAD_GATEWAY #返回哪个状态码需要进行重试，返回状态码为5XX进行重试
            backoff:
              firstBackoff: 10ms
              maxBackoff: 50ms
              factor: 2
              basedOnPreviousValue: false