server:
  port: 8202
spring:
  application:
    name: user-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://michael:123456@localhost:8001/eureka/ #配置注册中心地址