server:
  port: 8701
spring:
  application:
    name: feign-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://michael:123456@localhost:8001/eureka/ #配置注册中心地址
feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix
logging:
  level:
    com.dount.cloud.feignservice.service.UserService: debug